Csg/feature/encapsulate rpc result
chip-csg/connectedhomeip pull request #37
Opened 2021-06-28 21:14 UTC by nirav1911

#### Problem
What is being fixed?  Examples:
* Added introspection support for RPC Client

#### Change overview
What's in this PR

Added introspection support for RPC Client

#### Testing
How was this tested? (at least one bullet point required)
*Tested with test_client/rpc_client.py

2021-06-28 21:15 UTC, nirav1911 commented on src/controller/CHIPDeviceController.cpp
> +CHIP_ERROR DeviceController::GetFabricId(uint64_t & fabricId)
This file is not changed but I have worked on csg/test_event_3.1_fabric_id as base so all these changes are showing up in this PR.

2021-06-28 21:15 UTC, nirav1911 commented on src/controller/CHIPDeviceController.h
> +    /**
This file is not changed but I have worked on csg/test_event_3.1_fabric_id as base so all these changes are showing up in this PR.

2021-06-28 21:15 UTC, nirav1911 commented on src/controller/python/ChipDeviceController-ScriptBinding.cpp
> +CHIP_ERROR pychip_DeviceController_GetFabricId(chip::Controller::DeviceCommissioner * devCtrl, uint64_t * outFabricId);
This file is not changed but I have worked on csg/test_event_3.1_fabric_id as base so all these changes are showing up in this PR.

2021-06-28 21:15 UTC, nirav1911 commented on src/controller/python/chip-device-ctrl.py
> +        server.register_introspection_functions()
This is the only change in `chip-device-ctrl.py` file as part of this PR.

2021-06-28 21:16 UTC, nirav1911 commented on src/controller/python/test_client/rpc_client.py
> +def call_rpc(device_server,  method_name, *params):
Added this method to test call to RPC Server.

2021-06-29 14:16 UTC, mikaelhm requested changes
This looks good, but I think we need to make clean branch of `csg/test_event_3.1` and cherry-pick the commit, so we don't merge the changes from `csg/test_event_3.1_fabric_id` before they're ready.

2021-06-29 20:24 UTC, nirav1911 commented
> This looks good, but I think we need to make clean branch of `csg/test_event_3.1` and cherry-pick the commit, so we don't merge the changes from `csg/test_event_3.1_fabric_id` before they're ready.

Created a new PR: https://github.com/chip-csg/connectedhomeip/pull/39

2021-06-29 20:24 UTC, closed without merging